### ISSUE TITLE
Issue with drop downs in Chrome

### ISSUE THREAD

**Issue by DanHenebery** [densitydesign/raw#101]
Hi,

Drop down menus in the options and export sections do not appear to function in Chrome (Version 54.0.2840.71) for Desktop. Seems to work well on Chrome mobile and in Internet Explorer.

Thanks!

**Comment by DanHenebery** [comment]
To be clear: I can still interact with the drop down via the keyboard by using tab and shift-tab to select them. The issue seems to be specifically with mouse selection.

**Comment by mikima** [comment]
Do you still have this issue? I'm not able to reproduce it.

**Comment by tripplethrendo** [comment]
I noticed this issue last week, but Chrome must have updated and fixed itself...no longer seeing the problem.

**Comment by DanHenebery** [comment]
Tripplethrendo is correct. I too noticed that Chrome itself seems to have been the source and solution to this. I believe this should also closes several other open issues.
