### ISSUE TITLE
Error saving as PNG

### ISSUE THREAD

**Issue by rufuscreeley** [densitydesign/raw#102]
When I try to save as png nothing happens. The button doesn't work.
Thanks!

**Comment by Linneawikstrom** [comment]
I have the same issue. Will this be fixed soon? Or shall i try something else?

Thanks,
Linnea

**Comment by mikima** [comment]
Duplicate of #104 #105

**Comment by robroc** [comment]
Has this been fixed for all chart types? I'm getting the same problem with bump charts and streamgraphs specifically. On Chrome/Windows.
