### ISSUE TITLE
Is there a way to include multiple numbers?

### ISSUE THREAD

**Issue by lro1driven** [densitydesign/raw#103]
Hi All,

I'm sorry this is a very very basic question but today is the first time I have used Raw! I am loving it but having a few problems with my data (which is very simple)

I have 2 strings and each strings has 2 numbers but when I go to visualise I am not able to show both strings, with both of their values at the same time.

I can only show one string with both values. Is there any way to rectify this? On the charts I have been looking at I am only numbers are singular.

Any help would be much appreciated.

Many thanks

**Comment by mikima** [comment]
Hello,
can you provide a sample of the data? I'm not sure to have understood the problem

**Comment by mikima** [comment]
Probably you have multiple values in the same cell. In this case you must work on the dataset splitting them or in different columns, or in different rows, then reuploading it in RAWGraphs. OpenRefine could be a good solution:
https://github.com/OpenRefine/OpenRefine/wiki/Cell-Editing#splitting-multiple-values-within-cells-to-produce-records
