### ISSUE TITLE
[Safari/macOS] PNG download not working

### ISSUE THREAD

**Issue by mikima** [densitydesign/raw#104]
Only on Safari 10.0.1 on macOS Sierra.

Create viz, select 'image (PNG)', hit 'download'.
It will open a new tab with address `data:,`

**Comment by iosonosempreio** [comment]
☝🏾 http://ourcodeworld.com/articles/read/189/how-to-create-a-file-and-generate-a-download-with-javascript-in-the-browser-without-a-server
