### ISSUE TITLE
Date parsing: support time format

### ISSUE THREAD

**Issue by jimlynnjulian** [densitydesign/raw#106]
Hello,

   Just been trying out your software.  I have some solar data I need to chart dynamically and tried the scatter plot and the small multi-line graphs.
   The problem is my data is time variant and is in a text file in csv format. The time column is the first column in the dataset but is interpreted as strings by your software. Consequently, mapping the data along a time axis is impossible. You have Date, why not time? Seems time would be the obvious choice.

Thank you,
Jim J

**Comment by mikima** [comment]
Hi Jim,
with 'solar data' do you mean time in hours/minutes/seconds?
In RAW you must specify always a day of the year. Just add any date before your time, e.g.
`date	value
1/1/2016 12:30	9
1/1/2016 14:00	10
1/1/2016 15:40	3
1/1/2016 18:00	7
1/1/2016 20:00	9
1/1/2016 22:30	4`

If the day is the same for all the values, labels will show just the time.

**Comment by jimlynnjulian** [comment]
Hello,
   I've altered my data to the following. When I click the Table format, the data is out of sequence. Is the 24-hour format required for time? I'm using the 12-hour AM/PM format. 

    On Tuesday, January 10, 2017 4:38 AM, mikima <notifications@github.com> wrote:
 

 Hi Jim,
with 'solar data' do you mean time in hours/minutes/seconds?
In RAW you must specify always a day of the year. Just add any date before your time, e.g.
date value 1/1/2016 12:30 9 1/1/2016 14:00 10 1/1/2016 15:40 3 1/1/2016 18:00 7 1/1/2016 20:00 9 1/1/2016 22:30 4If the day is the same for all the values, labels will show just the time.—

**Comment by jimlynnjulian** [comment]
Hello,
   I altered my data again.date-time 24,time 12,PV array voltage(V),PV array power(W),Ppv / 10,Battery voltage(V),Battery SOC(%),SOC% / 2,azimuth,elevation
11/21/16 06:55:00,06:55:00 AM,23.9,0,0,24.12,17,8.5,112.0093435263,-2.5857869395
and the program STILL won't take the data. Your program needs work. Too finicky on time format. Time is the most common X-axis variable. Oversight supreme.
    

    On Tuesday, January 10, 2017 4:38 AM, mikima <notifications@github.com> wrote:
 

 Hi Jim,
with 'solar data' do you mean time in hours/minutes/seconds?
In RAW you must specify always a day of the year. Just add any date before your time, e.g.
date value 1/1/2016 12:30 9 1/1/2016 14:00 10 1/1/2016 15:40 3 1/1/2016 18:00 7 1/1/2016 20:00 9 1/1/2016 22:30 4If the day is the same for all the values, labels will show just the time.—

**Comment by mikima** [comment]
Hello, thank you. You're right, we must improve the data parsing. As soon as possible we will fix the bug.

**Comment by mikima** [comment]
With the new version ([1.2.0](v1.2.0)) more date formats are supported.
test it here: app.rawgraphs.io

The 'time' format is still not supported by RAW, but if you insert the full date it works:
e.g. `11/21/16 06:55:00` is now correctly recognized as date.

Let us know if this update solves your issue.
