### ISSUE TITLE
Can't see the entire last entry in the heirarchy

### ISSUE THREAD

**Issue by tripplethrendo** [densitydesign/raw#107]
When using 5 levels in the Cluster Dendogram, the last group in the hierarchy gets shortened.
![short](https://cloud.githubusercontent.com/assets/5719709/21812929/604e9ac0-d709-11e6-9a0a-3529c1c22603.png)

I've tried adjusting height and width to no avail.

**Comment by mikima** [comment]
seems that due the amount of levels, the software is not able to give enough space to labels.
Anyway, the labels are just cropped: if you open the svg in inkscape/illustrator or similar, you'll see the full label. this could be a workaround while we'll fix it.

**Comment by tripplethrendo** [comment]
Thank you that is extremely helpful.

**Comment by mikima** [comment]
Probably fixed with cc379fad326b3e5997db1b2ef5753a64d17892ea, to be checked.
