### ISSUE TITLE
"Tune your chart" toolbar disapear while using Bar Chart model 

### ISSUE THREAD

**Issue by AnderTave** [densitydesign/raw#142]
Browser version: Firefox 54.0.1 (32 bit)
I am using a Windows 10 pc.

The toolbar under "Customize your Visualization" is hidden if the "Width" is set to high.

As you can see from the screens it seems the viz overlap the toolbar.

![sketch_raw](https://user-images.githubusercontent.com/11838774/28565707-3f3de994-712d-11e7-98a2-dc1ef0912fad.png)

![sketch_raw2](https://user-images.githubusercontent.com/11838774/28565706-3f270882-712d-11e7-9e48-f994f45f83ae.png)

This bug does not happen on Chrome or either (brace yourself) Miscrosoft Edge

Andrea

**Comment by mikima** [comment]
update: it happens on all the visual models.
It happens also on mac (tested with Firefox 56.0 64 bit)
