### ISSUE TITLE
Suggested fix for Sunburst upside down labels

### ISSUE THREAD

**Issue by ehausen** [densitydesign/raw#144]
The sunburst rotates labels so that they end up upside down on left side.
Example of the problem:
![screen shot 2017-08-14 at 18 56 22](https://user-images.githubusercontent.com/6204129/29280013-52758166-8122-11e7-86dc-63b23e92eeb6.png)

Suggested fix:
Fix this as in this example from: http://jsfiddle.net/5d0zd2s7/ (source: https://stackoverflow.com/questions/29884995/adding-labels-to-d3-sunburst)

```
function getAngle(d) {
    // Offset the angle by 90 deg since the '0' degree axis for arc is Y axis, while
    // for text it is the X axis.
    var thetaDeg = (180 / Math.PI * (arc.startAngle()(d) + arc.endAngle()(d)) / 2 - 90);
    // If we are rotating the text by more than 90 deg, then "flip" it.
    // This is why "text-anchor", "middle" is important, otherwise, this "flip" would
    // a little harder.
    return (thetaDeg > 90) ? thetaDeg - 180 : thetaDeg;
}
```

**Comment by mikima** [comment]
Thanks for the suggestion! We will try to fix it.
