### ISSUE TITLE
Blank pages on install

### ISSUE THREAD

**Issue by goodnewseveryone99** [densitydesign/raw#145]
When cloning the site and accessing the site, the page has only the navigation bar on the top and everything else is blank. ???
![raw](https://user-images.githubusercontent.com/31189653/29497271-4ea4093c-85b3-11e7-89ad-06d9c01f8684.PNG)

**Comment by mikima** [comment]
Hi, after cloning it, you have to install bower dependencies.
See here how:
https://github.com/densitydesign/raw#installation
