### ISSUE TITLE
Option to sort numerically in Alluvial Diagram

### ISSUE THREAD

**Issue by Triphammer** [densitydesign/raw#153]
Whan creating an Alluvial Diagram, the sorting can only be done by Name, which is alphabetic.  Ability to sort numerically on a numeric column would be useful.

Consider the following simple dataset:
INITIAL DATASET, FINAL RANKING
A,8
A,4
A,1
B,7
B,2
B,3
C,5
C,6
C,9
A,10
B,11

Creating an alluvial diagram with steps of INITIAL DATASET and FINAL RANKING shows the FINAL RANKING column as 1,10,11,2,3,4,5,6,7,8,9 (alphabetical order) rather than sorted numerically.  I can't see any practical use for a number column to be sorted alphabetically.

REQUEST:  If a STEP column is a number, NAME sorting should sort numerically rather than alphabetically.

**Comment by namanjain1812** [comment]
@Triphammer Is this feature present nowt.As i am interested in it

**Comment by Triphammer** [comment]
Not that I am aware of.  I haven't had any response at all about it.

**Comment by mikima** [comment]
Fixed in master, feature will be present in the next release, see image below.

![ranking-numerically -and-alphabetically](https://user-images.githubusercontent.com/907536/40648026-a60cf29e-632d-11e8-9003-3c9b297c20b0.png)

**Comment by Triphammer** [comment]
I'm speechless.  Perfect.  Thank you so very much.
