### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by VStyles** [densitydesign/raw#157]
I'm unable to load the site.

receiving error "This site can’t be reached" "app.rawgraphs.io’s server IP address could not be found." "ERR_NAME_NOT_RESOLVED"

tried on a different device an internet connection as well but the same result. Disabled ad blockers, opened in an incognito window, tested on Google Chrome & Mozilla Firefox Q.

**Comment by mikima** [comment]
Hello, we were updating our server. Now the website is back online.
