### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by G1ANP13R0** [densitydesign/raw#158]
Hi,

I'd like install raw from git bash.
I have installed git and bower first, but when i launch "_git clone https://github.com/densitydesign/raw.git_"  the connection go in timeout.
Could you help?
I use a corrporate proxy for web connection. I need to set up it in git?
Thanks,

Gianpiero

**Comment by mikima** [comment]
Hello Gianpiero,
the command is correct, it should work.
Have you tried using a different connection?

**Comment by mikima** [comment]
@G1ANP13R0 is this issue still open?
