### ISSUE TITLE
Please handle non-populated fields - instead of fail.

### ISSUE THREAD

**Issue by AndKe** [densitydesign/raw#160]
[Battery.zip](https://github.com/densitydesign/raw/files/2042478/Battery.zip)

The attached file contain data from different sources, not all columns are populated every time.
- it fail to graph/load.

**Comment by mikima** [comment]
Hi, RAWGraphs handles non-populated values, but all the lines must contain the same amount of cells.

In the dataset you uploaded the last line (10883) is truncated. See here the last two lines:

    998608,379.99,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
    998693,3

If you add commas to the last line, it will work.
Try with this correct dataset:

[Battery-fixed.csv.zip](https://github.com/densitydesign/raw/files/2049090/Battery-fixed.csv.zip)

**Comment by AndKe** [comment]
fantastic, thank you :)

**Comment by AndKe** [comment]
BTW: still unable to test because https://rawgraphs.io/
gives me: 
This site can’t be reached
rawgraphs.io’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by mikima** [comment]
@AndKe that's strange, it seems to be a DNS problem. Is it still unreachable fro you?

**Comment by AndKe** [comment]
Solved: were travelling, using Private Internet Access (VPN service)  - proved to have a DNS that did not had your site, notified them , and it works both with, and without VPN now.
