### ISSUE TITLE
Namespace issue in Bump Chart

### ISSUE THREAD

**Issue by Mitch90** [densitydesign/raw#161]
There is a namespace issue in the exporting of the svg in the Bump Chart (could also be in other visual models, but I've found it for sure in the Bump Chart). 
It would easly be fixable by adding this line as an attribute to the svg element:

``xmlns:xlink="http://www.w3.org/1999/xlink"``

Here attached the error I'm talking about:
![screen shot 2018-05-28 at 11 09 56](https://user-images.githubusercontent.com/7771123/40607320-6d70d2b8-6268-11e8-9b65-eeecd642c45e.png)

**Comment by mikima** [comment]
Solved with cc379fad326b3e5997db1b2ef5753a64d17892ea
