### ISSUE TITLE
Svgs break when they have a text on path but don't have xlink attribute in the svg element

### ISSUE THREAD

**Issue by Mitch90** [densitydesign/raw#172]
Exporting any chart with the checkbox "Show Labels" will generate a broken svg.
This is easily fixable by always adding the attribute `xmlns:xlink="http://www.w3.org/1999/xlink"` to the svg element (it won't be necessary when there is no text on path, but it doesn't hurt to add it anyway)

**Comment by mikima** [comment]
closed in /dev branch
