### ISSUE TITLE
dc.js integration - [Enhancement]

### ISSUE THREAD

**Issue by tomsutton1984** [densitydesign/raw#56]
Would be great to see dc.js compatibility!

https://github.com/dc-js/dc.js/wiki

**Comment by adrianbj** [comment]
Was anything ever started on this idea?

Would this angular directive for dc.js (https://github.com/TomNeyland/angular-dc) be useful?

I am looking at adding support for dc.js or c3.js into Raw.

**Comment by uf0** [comment]
The aims of the 2 project are quite different. Since no additional information about the integration are provided, we close the issue.
