### ISSUE TITLE
Insert CSV data by URL

### ISSUE THREAD

**Issue by ghirardinicola** [densitydesign/raw#66]
My scope is to call raw passing a URL param representing the address of the remote CSV.
RAW should download the data and parse it.
Any hint in how to start?
Thanks

**Comment by mikima** [comment]
Added early support for loading csv files from url in [1.2.0](https://github.com/densitydesign/raw/releases/tag/v1.2.0).

For now it works only whit CORS-enabled sources, see the 1.2.0 changelog.
