### ISSUE TITLE
Integrating NVD3.js chart types as layouts in RAW

### ISSUE THREAD

**Issue by timopulkkinen** [densitydesign/raw#73]
Hello,

besides more advanced chart/layout types already provided, would it be possible to include basic chart types, for example using http://nvd3.org ? Although a pie chart is a bit boring, some users prefer those...

Any comments / estimates on work needed to implement this? I might do some implementation work myself, if this doesn't require like a complete rewrite of the RAW architecture or such :)

br,
Timo

**Comment by adrianbj** [comment]
I am also interested in this, or some other library for basic chart types - I quite like C3js (http://c3js.org/) at the moment. There is an angular directive for it (http://jettro.github.io/c3-angular-directive/) that might be helpful for an integration.

Before I tackle this myself, has anyone done any work on NVD3 or any other charting library integration?

**Comment by uf0** [comment]
As with dc.js #56: the aims of the 2 project are quite different. Since no additional information about the integration are provided, we close the issue.
