### ISSUE TITLE
svg error: "xmlParseEntityRef: no name" caused by unescaped special charachters ampersands (&) and apostrophes

### ISSUE THREAD

**Issue by orr2xh** [densitydesign/raw#79]
Hi I can't seem to get my alluvial design to download into a working svg. 

This is what the rendering of the svg looks like
![screen shot 2014-10-02 at 8 14 43 pm](https://cloud.githubusercontent.com/assets/8900546/4500459/8b55f944-4a92-11e4-9cfc-21b27ecaa83a.png)

As you can see the second step's nodes and labels are missing. 

When I try and place it in AI, I get the following error message:

"This SVG is invalid. Validate before opening."

My data is in csv form, but I have also tried it in excel, and have the same issue. 

Thanks!
OR

**Comment by prcweb** [comment]
I've got round this by copying the from the Embed Code text area (just to the right of the Download area), pasting into a text file and saving as myfile.svg.

**Comment by krisztianfekete** [comment]
This is similar to #95 (closed but still an issue)
