### ISSUE TITLE
Clustered Force Layout: missing CX and CY values in "Embed Code"

### ISSUE THREAD

**Issue by efath1** [densitydesign/raw#80]
Hi,

I'm experiencing the strangest problem--Raw is parsing and exporting my data successfully to an SVG, but when pasted into an html document, only the text shows up, clustered together at the top of the page.

I've tried tweaking it and reducing the data down to just one circle, but it won't draw even one.  

Here is a link to the code snippet: https://gist.github.com/efath1/898dee3ac683c4977937

Any help is greatly appreciated!

**Comment by mikima** [comment]
Creating a "Clustered Force Layout", the SVG code preview in the "embed code" field is wrong. CX and CY values of circles is not present.
Anyway, downloading the SVG code is correct.

**Comment by mikima** [comment]
As described by @uf0 (https://github.com/vathsav/raw/commit/5a7b4d3ac0e8b5cde83c98a39dc78427610d1c94#commitcomment-20611620) to solve this issue we should to fire an additional event when the spatialization is done, and then address it in the directive.

**Comment by uf0** [comment]
we fixed here 9ea431189775f3be68eccb6c7f2771a2751843b7 thanks to @vathsav
