### ISSUE TITLE
Years are separated with a coma in graphs

### ISSUE THREAD

**Issue by tonybruce** [densitydesign/raw#85]
- choose a data with a year value e.g. sample data music
- choose the bump chart
- add the year number to date, market share to size and media to group
- look at the chart and notice the years are separated with a coma by thousands and the edge numbers are incomplete 

*Note:
Reproducible on both X and Y axis.

**Comment by mikima** [comment]
For now, years are formatted as numbers, therefore the the comma is used as thousands separator.
Numbers are cropped to the artboard but complete.
You can solve both problems downloading the SVG file and editing it in a vector editor (like inkscape, sketch or illustrator).
