### ISSUE TITLE
Missing X and Y labels for Convex Hull graph

### ISSUE THREAD

**Issue by tonybruce** [densitydesign/raw#86]
- select Cars data
- choose Convex Hull graph
- set year for X axis and cylinders for Y axis and notice there are no labels or values on the graph

**Comment by mikima** [comment]
Yes, the 'convex hull' visual model is still very experimental, we'll improve it in the next release.

**Comment by mikima** [comment]
Added labels in [version 1.2.0](https://github.com/densitydesign/raw/releases/tag/v1.2.0)
