### ISSUE TITLE
Visualization in Steamgraphchart showing incorrect results when single value gets edited

### ISSUE THREAD

**Issue by JokinAspiazu** [densitydesign/raw#87]
Repro steps:
Select example music datafile.
Select Steamgraph visualization and complete the axis thing.

... we get the visualization as seen on the upper left corner.

Then edit the data, alter a single value with a value of 1000 market share.

Redo the visualization.

It is observed that the data that can be seen ordered BEFORE in time than the value that we edited changed from 50 to almost 500.

It was expected that the values from years after the edited value, still got the same values as the ones from years after the edited value.

![presentation_bug](https://cloud.githubusercontent.com/assets/1241202/6410482/fcb2ae60-be6f-11e4-8c60-be688cb9ec9e.png)

**Comment by mikima** [comment]
Not sure to have understood the problem.
In RAW, the visualization is scaled according the maximum value.
In the second visualization, data didn't change, it is scaled to fit the maximum value in the given visualization height.
If you want to keep the same scale, you should increase the visualization height by ~10 times.

If I misunderstood the question, please let me know.

**Comment by JokinAspiazu** [comment]
The problem is not with the data that have been altered in order to test the feature. The problem seems to be with how the previous data are displayed.

Compare 8-track, Vinyl and CD in both images. Only altering the amount of vinyl to 1000 we get a 8-track display close to 500 (red square on bottom capture)

**Comment by mikima** [comment]
Not sure what do you mean with
> close to 500 (red square on bottom capture)

If you are referring to the Y axis, you are misreading the visualization.

In the streamgraph the value (in your case, the market share) is not mapped on the y position, but on the thickness of the stream, see: https://en.wikipedia.org/wiki/Streamgraph
