### ISSUE TITLE
Embed code error

### ISSUE THREAD

**Issue by anihovh** [densitydesign/raw#88]
When I paste the embed code of the visualization in my website, it doesn't work, it doesn't work also in html tester, but it normally shows in RAW.

**Comment by giorgiocaviglia** [comment]
I apologize for the delayed answer. Can you provide an example of the code not working? We know about a problem when some chars appear in your data (e.g. `&`). We are going to fix all this very soon.
Thanks

**Comment by uf0** [comment]
We fixed some bugs related to svg validation.
But since no additional information were provided, we will close the issue.
