### ISSUE TITLE
How to customize colors generated by chart.color()

### ISSUE THREAD

**Issue by CorpusCallosum** [densitydesign/raw#90]
Is there some way to change the default colors that are generated by using the chart.color.domain() method? For example, if I want to have a list of custom colors, instead of the default "rainbow" that is created by the ordinal domain mapping.

**Comment by mikima** [comment]
You can add your own color scale here: https://github.com/densitydesign/raw/blob/master/js/directives.js#L201

And will be displayed in the drop-down menu, as in this screenshot:
<img width="281" alt="screen shot 2017-01-25 at 17 10 53" src="https://cloud.githubusercontent.com/assets/907536/22298571/49fd4e14-e321-11e6-9599-7ba12406a543.png">

Try to uncomment [here](https://github.com/densitydesign/raw/blob/master/js/directives.js#L209) to see the result.
