### ISSUE TITLE
Integrating new d3.js chart as layout in raw.js

### ISSUE THREAD

**Issue by hhsadiq** [densitydesign/raw#92]
Is there any official API or guiding docs which can be used to integrate new layouts in raw.js. I cannot find anyone. And if there is not, can someone give me suggestion that is it possible or not...? And if possible, is it difficult task which will take weeks to accomplish...? or simple which can be completed with less effort.

**Comment by iosonosempreio** [comment]
Hi @hhsadiq, take a look here: https://github.com/densitydesign/raw/wiki/Adding-New-Charts
