### ISSUE TITLE
SVG and PNG files won't validate in Illustrator and InDesign respectively

### ISSUE THREAD

**Issue by margyavery** [densitydesign/raw#95]
Hi, this is an amazing tool and I'm excited to use it. I'd like to be able to modify the output however Illustrator and InDesign won't open the files citing validation issues. W3C markup validator suggests there's no character encoding declared at the document level. Help? thank you!

**Comment by mikima** [comment]
Can you please share the SVG? thanks!

**Comment by margyavery** [comment]
Apologies - just seeing this now. will upload asap.

**Comment by margyavery** [comment]
Hi, I cannot attach the .svg file but here's the PNG. I'm most interested in opening the .svg file in InDesign - let me know the best way to get you this file? thank you!
![ssrn-aarn](https://cloud.githubusercontent.com/assets/1615523/12870437/d86879a6-cd12-11e5-88c5-f11b4eb9a259.png)

**Comment by adrianbj** [comment]
I have no problem "placing" the PNG into InDesign. Remember that InDesign won't directly open PNG files. 

You should be able to post the SVG if you change the file extension to "txt" or archive to a zip first.

**Comment by mikima** [comment]
Yes, i suggerst you to upload a zip file containing the svg, like one i'm attaching as example.
[bump_chart.zip](https://github.com/densitydesign/raw/files/120699/bump_chart.zip)

**Comment by margyavery** [comment]
Thank you for your assistance on this more remedial stuff. I'm sure it's clear I'm more of a text person. Trying to visualize text. 
[SSRN-aarn.txt.zip](https://github.com/densitydesign/raw/files/120819/SSRN-aarn.txt.zip)

**Comment by adrianbj** [comment]
It's an entity encoding issue. If you do a find and replace on "&" with "&amp;" the file will open just fine in Illustrator.

**Comment by mikima** [comment]
@adrianbj thanks, that's the problem. If you use as label a string containing "&" it will create a broken SVG.
To solve it, use @adrianbj solution (find and replace `&` with `&amp;`)

**Comment by krisztianfekete** [comment]
Does closing the issue mean this trivial looking bug will not be fixed?

I do not know enough javascript to fix it myself without burning away an uncomfortable amount of time, but searching through the code the fix should probably go here:
https://github.com/densitydesign/raw/blob/e2e49992c576999380986c6858ceb29a274bcf71/js/directives.js#L511

**Comment by adrianbj** [comment]
I agree with @krisztianfekete - my "fix" was only meant to be a quick way for @margyavery to able to open the SVG.

**Comment by margyavery** [comment]
I actually don't know how to do complete the process you suggested without spending a good hour on it, unfortunately.

**Comment by adrianbj** [comment]
You can make the change by opening the SVG file in a simple text editor (not a Word Processor), and do a search/find and replace.

This is something that Raw needs to fix properly, so this is just meant to be a stopgap measure so you can open the files.

**Comment by margyavery** [comment]
Thank you for this information @adrianbj -  much appreciated. :) This is an amazing tool!
