### ISSUE TITLE
How can I redraw charts programatically?

### ISSUE THREAD

**Issue by TomasZorvan** [densitydesign/raw#96]
Hi,
is there a way to redraw chart from my code? Im looking for something like `chart.redraw()` so it redraw chart with e.g. new properties. Chart can be redrawn when user clicks checkbox and so on but I need to use it like function call. 

Thanks for any help

**Comment by uf0** [comment]
I'm not sure I've understood your problem. If you add and option to a chart and you change it through the interface (checkbox, number field, etc.) the `draw()` function is automatically called and the visualization redrawn.

Btw if you want to redraw the chart you can use this function:
https://github.com/densitydesign/raw/blob/master/js/directives.js#L144
